/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_bool = 1,
  anon_sym_byte = 2,
  anon_sym_int = 3,
  anon_sym_uint = 4,
  anon_sym_long = 5,
  anon_sym_ulong = 6,
  anon_sym_char = 7,
  anon_sym_string = 8,
  anon_sym_array = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_of = 13,
  sym_identifier = 14,
  sym_source = 15,
  sym_typeRef = 16,
  aux_sym_source_repeat1 = 17,
  aux_sym_typeRef_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_bool] = "bool",
  [anon_sym_byte] = "byte",
  [anon_sym_int] = "int",
  [anon_sym_uint] = "uint",
  [anon_sym_long] = "long",
  [anon_sym_ulong] = "ulong",
  [anon_sym_char] = "char",
  [anon_sym_string] = "string",
  [anon_sym_array] = "array",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_of] = "of",
  [sym_identifier] = "identifier",
  [sym_source] = "source",
  [sym_typeRef] = "typeRef",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_typeRef_repeat1] = "typeRef_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_byte] = anon_sym_byte,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_long] = anon_sym_long,
  [anon_sym_ulong] = anon_sym_ulong,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_of] = anon_sym_of,
  [sym_identifier] = sym_identifier,
  [sym_source] = sym_source,
  [sym_typeRef] = sym_typeRef,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_typeRef_repeat1] = aux_sym_typeRef_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_byte] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_long] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ulong] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_typeRef] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeRef_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_array = 1,
  field_builtin = 2,
  field_custom = 3,
  field_typeRef = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_array] = "array",
  [field_builtin] = "builtin",
  [field_custom] = "custom",
  [field_typeRef] = "typeRef",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 5},
  [7] = {.index = 11, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_builtin, 0},
  [1] =
    {field_custom, 0},
  [2] =
    {field_typeRef, 0},
  [3] =
    {field_typeRef, 0, .inherited = true},
  [4] =
    {field_typeRef, 0, .inherited = true},
    {field_typeRef, 1, .inherited = true},
  [6] =
    {field_array, 0},
    {field_array, 1},
    {field_array, 2},
    {field_array, 3},
    {field_array, 4},
  [11] =
    {field_array, 0},
    {field_array, 1},
    {field_array, 2},
    {field_array, 3},
    {field_array, 4},
    {field_array, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        ',', 51,
        '[', 50,
        ']', 52,
        'a', 23,
        'b', 19,
        'c', 8,
        'i', 14,
        'l', 18,
        'o', 4,
        's', 28,
        'u', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == 'g') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 7:
      if (lookahead == 'g') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(2);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(1);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 29:
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == 'a') ADVANCE(75);
      if (lookahead == 'b') ADVANCE(71);
      if (lookahead == 'c') ADVANCE(60);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead == 'l') ADVANCE(70);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead == 'u') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_byte);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_byte);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_uint);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_uint);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_long);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_long);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_ulong);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_ulong);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_char);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_array);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == 'l') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(69);
      if (lookahead == 'y') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_byte] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_long] = ACTIONS(1),
    [anon_sym_ulong] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(15),
    [sym_typeRef] = STATE(6),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_bool] = ACTIONS(5),
    [anon_sym_byte] = ACTIONS(5),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_uint] = ACTIONS(5),
    [anon_sym_long] = ACTIONS(5),
    [anon_sym_ulong] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_string] = ACTIONS(5),
    [anon_sym_array] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_typeRef] = STATE(6),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(5),
    [anon_sym_byte] = ACTIONS(5),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_uint] = ACTIONS(5),
    [anon_sym_long] = ACTIONS(5),
    [anon_sym_ulong] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_string] = ACTIONS(5),
    [anon_sym_array] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_typeRef] = STATE(6),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_byte] = ACTIONS(15),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_uint] = ACTIONS(15),
    [anon_sym_long] = ACTIONS(15),
    [anon_sym_ulong] = ACTIONS(15),
    [anon_sym_char] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_array] = ACTIONS(18),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(24),
    [anon_sym_bool] = ACTIONS(26),
    [anon_sym_byte] = ACTIONS(26),
    [anon_sym_int] = ACTIONS(26),
    [anon_sym_uint] = ACTIONS(26),
    [anon_sym_long] = ACTIONS(26),
    [anon_sym_ulong] = ACTIONS(26),
    [anon_sym_char] = ACTIONS(26),
    [anon_sym_string] = ACTIONS(26),
    [anon_sym_array] = ACTIONS(26),
    [sym_identifier] = ACTIONS(26),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(28),
    [anon_sym_bool] = ACTIONS(30),
    [anon_sym_byte] = ACTIONS(30),
    [anon_sym_int] = ACTIONS(30),
    [anon_sym_uint] = ACTIONS(30),
    [anon_sym_long] = ACTIONS(30),
    [anon_sym_ulong] = ACTIONS(30),
    [anon_sym_char] = ACTIONS(30),
    [anon_sym_string] = ACTIONS(30),
    [anon_sym_array] = ACTIONS(30),
    [sym_identifier] = ACTIONS(30),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_bool] = ACTIONS(34),
    [anon_sym_byte] = ACTIONS(34),
    [anon_sym_int] = ACTIONS(34),
    [anon_sym_uint] = ACTIONS(34),
    [anon_sym_long] = ACTIONS(34),
    [anon_sym_ulong] = ACTIONS(34),
    [anon_sym_char] = ACTIONS(34),
    [anon_sym_string] = ACTIONS(34),
    [anon_sym_array] = ACTIONS(34),
    [sym_identifier] = ACTIONS(34),
  },
  [STATE(7)] = {
    [sym_typeRef] = STATE(8),
    [anon_sym_bool] = ACTIONS(5),
    [anon_sym_byte] = ACTIONS(5),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_uint] = ACTIONS(5),
    [anon_sym_long] = ACTIONS(5),
    [anon_sym_ulong] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_string] = ACTIONS(5),
    [anon_sym_array] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(36),
    [anon_sym_bool] = ACTIONS(38),
    [anon_sym_byte] = ACTIONS(38),
    [anon_sym_int] = ACTIONS(38),
    [anon_sym_uint] = ACTIONS(38),
    [anon_sym_long] = ACTIONS(38),
    [anon_sym_ulong] = ACTIONS(38),
    [anon_sym_char] = ACTIONS(38),
    [anon_sym_string] = ACTIONS(38),
    [anon_sym_array] = ACTIONS(38),
    [sym_identifier] = ACTIONS(38),
  },
  [STATE(9)] = {
    [sym_typeRef] = STATE(10),
    [anon_sym_bool] = ACTIONS(5),
    [anon_sym_byte] = ACTIONS(5),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_uint] = ACTIONS(5),
    [anon_sym_long] = ACTIONS(5),
    [anon_sym_ulong] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_string] = ACTIONS(5),
    [anon_sym_array] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(40),
    [anon_sym_bool] = ACTIONS(42),
    [anon_sym_byte] = ACTIONS(42),
    [anon_sym_int] = ACTIONS(42),
    [anon_sym_uint] = ACTIONS(42),
    [anon_sym_long] = ACTIONS(42),
    [anon_sym_ulong] = ACTIONS(42),
    [anon_sym_char] = ACTIONS(42),
    [anon_sym_string] = ACTIONS(42),
    [anon_sym_array] = ACTIONS(42),
    [sym_identifier] = ACTIONS(42),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(46), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym_typeRef_repeat1,
  [10] = 3,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    ACTIONS(50), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      aux_sym_typeRef_repeat1,
  [20] = 3,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      aux_sym_typeRef_repeat1,
  [30] = 1,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
  [34] = 1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
  [38] = 1,
    ACTIONS(61), 1,
      anon_sym_of,
  [42] = 1,
    ACTIONS(63), 1,
      anon_sym_of,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 10,
  [SMALL_STATE(13)] = 20,
  [SMALL_STATE(14)] = 30,
  [SMALL_STATE(15)] = 34,
  [SMALL_STATE(16)] = 38,
  [SMALL_STATE(17)] = 42,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 5),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 5), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 5), SHIFT_REPEAT(14),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 5), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeRef, 1, 0, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeRef, 1, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeRef, 1, 0, 2),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeRef, 1, 0, 2),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 3),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 1, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeRef, 5, 0, 6),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeRef, 5, 0, 6),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeRef, 6, 0, 7),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeRef, 6, 0, 7),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeRef_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeRef_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_var2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "var2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
