/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BANG = 1,
  anon_sym_TILDE = 2,
  anon_sym_DASH = 3,
  anon_sym_PLUS = 4,
  anon_sym_COLON_EQ = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_PERCENT = 8,
  anon_sym_PIPE_PIPE = 9,
  anon_sym_AMP_AMP = 10,
  anon_sym_PIPE = 11,
  anon_sym_CARET = 12,
  anon_sym_AMP = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_GT = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_LT = 20,
  anon_sym_GT_GT = 21,
  sym_identifier = 22,
  sym_source_file = 23,
  sym_expression = 24,
  sym_unary_expression = 25,
  sym_binary_expression = 26,
  aux_sym_source_file_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_binOp = 1,
  field_binary = 2,
  field_expr = 3,
  field_operator = 4,
  field_place = 5,
  field_unary = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_binOp] = "binOp",
  [field_binary] = "binary",
  [field_expr] = "expr",
  [field_operator] = "operator",
  [field_place] = "place",
  [field_unary] = "unary",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_place, 0},
  [1] =
    {field_expr, 0},
  [2] =
    {field_unary, 0},
  [3] =
    {field_binary, 0},
  [4] =
    {field_expr, 0, .inherited = true},
  [5] =
    {field_expr, 1},
    {field_operator, 0},
  [7] =
    {field_expr, 0, .inherited = true},
    {field_expr, 1, .inherited = true},
  [9] =
    {field_binOp, 1},
    {field_expr, 0},
    {field_expr, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 4,
        '%', 11,
        '&', 16,
        '*', 9,
        '+', 7,
        '-', 6,
        '/', 10,
        ':', 1,
        '<', 22,
        '=', 2,
        '>', 19,
        '^', 15,
        '|', 14,
        '~', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(12);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(13);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_expression] = STATE(5),
    [sym_unary_expression] = STATE(6),
    [sym_binary_expression] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BANG] = ACTIONS(5),
    [anon_sym_TILDE] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
  [STATE(2)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_COLON_EQ] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_PIPE_PIPE] = ACTIONS(27),
    [anon_sym_AMP_AMP] = ACTIONS(27),
    [anon_sym_PIPE] = ACTIONS(29),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [sym_identifier] = ACTIONS(27),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_COLON_EQ] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(31),
    [anon_sym_AMP] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_BANG_EQ] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(33),
    [anon_sym_LT_LT] = ACTIONS(31),
    [anon_sym_GT_GT] = ACTIONS(31),
    [sym_identifier] = ACTIONS(31),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_TILDE] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(41),
    [anon_sym_AMP_AMP] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_TILDE] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_COLON_EQ] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym_PERCENT] = ACTIONS(49),
    [anon_sym_PIPE_PIPE] = ACTIONS(49),
    [anon_sym_AMP_AMP] = ACTIONS(49),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(51),
    [anon_sym_LT_LT] = ACTIONS(49),
    [anon_sym_GT_GT] = ACTIONS(49),
    [sym_identifier] = ACTIONS(49),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_TILDE] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_COLON_EQ] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(53),
    [anon_sym_PERCENT] = ACTIONS(53),
    [anon_sym_PIPE_PIPE] = ACTIONS(53),
    [anon_sym_AMP_AMP] = ACTIONS(53),
    [anon_sym_PIPE] = ACTIONS(55),
    [anon_sym_CARET] = ACTIONS(53),
    [anon_sym_AMP] = ACTIONS(55),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(53),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(55),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_GT_GT] = ACTIONS(53),
    [sym_identifier] = ACTIONS(53),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_LT] = ACTIONS(9),
    [anon_sym_GT_GT] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_LT] = ACTIONS(9),
    [anon_sym_GT_GT] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(41),
    [anon_sym_AMP_AMP] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_GT_GT] = ACTIONS(25),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_LT] = ACTIONS(9),
    [anon_sym_GT_GT] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_expression,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [25] = 7,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(5), 1,
      sym_expression,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(61), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [50] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(11), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [69] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(12), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [88] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(13), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [107] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(9), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [126] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(10), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [145] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(15), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [164] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(2), 1,
      sym_expression,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [183] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(14), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [202] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(17), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [221] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(4), 1,
      sym_expression,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [240] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(16), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [259] = 5,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(6), 1,
      sym_unary_expression,
    STATE(7), 1,
      sym_binary_expression,
    STATE(8), 1,
      sym_expression,
    ACTIONS(5), 4,
      anon_sym_BANG,
      anon_sym_TILDE,
      anon_sym_DASH,
      anon_sym_PLUS,
  [278] = 1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 25,
  [SMALL_STATE(20)] = 50,
  [SMALL_STATE(21)] = 69,
  [SMALL_STATE(22)] = 88,
  [SMALL_STATE(23)] = 107,
  [SMALL_STATE(24)] = 126,
  [SMALL_STATE(25)] = 145,
  [SMALL_STATE(26)] = 164,
  [SMALL_STATE(27)] = 183,
  [SMALL_STATE(28)] = 202,
  [SMALL_STATE(29)] = 221,
  [SMALL_STATE(30)] = 240,
  [SMALL_STATE(31)] = 259,
  [SMALL_STATE(32)] = 278,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 8),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 6),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 6),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 2),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 7),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 7), SHIFT_REPEAT(29),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 7), SHIFT_REPEAT(3),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_var2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "var2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
